let redArmy = [];
let blueArmy = [];
export {redArmy};
export {blueArmy};
let redTowers = [];
let blueTowers = [];
export {redTowers};
export {blueTowers};
let countRed =  [0,0];
let countBlue = [0,0];
export {countRed};
export {countBlue};
let pauseBoolean = [true];
export { pauseBoolean };
let gameOver = [true];
export { gameOver };
