const canvas = document.getElementById("canvas");
const ctx = canvas.getContext("2d");
export { ctx };
export { canvas };
let objMap = new Map();
export { objMap };
let redArmy = [];
let blueArmy = [];
export { redArmy };
export { blueArmy };
let redTowers = [];
let blueTowers = [];
export { redTowers };
export { blueTowers };
let countRed = [0, 0];
let countBlue = [0, 0];
export { countRed };
export { countBlue };
let pauseBoolean = [false];
export { pauseBoolean };
let gameOver = [true];
export { gameOver };
let mainMusic = [document.getElementById ('main_music')];
mainMusic[0].volume = 0.3;
export { mainMusic };

